version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/development/python/Dockerfile
    image: learn-django-app
    # stdin_open: true
    # tty: true
    container_name: learn_django
    ports: 
      - "8000:8000"
    volumes:
      - ./:/app

networks:
  default:
    name: learn_django