# Generated by Django 2.2 on 2024-03-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='person_genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='person_bithday',
            new_name='nascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='person_name',
            new_name='nome',
        ),
    ]
